import { Navbar } from "@/components/navbar";

export const metadata = { title: "Privacy Policy — Aria" };

export default function PrivacyPage() {
  return (
    <div className="min-h-dvh">
      <Navbar />
      <article className="mx-auto max-w-2xl px-4 py-16 [&_h2]:mt-10 [&_h2]:font-display [&_h2]:text-xl [&_h2]:font-bold [&_p]:mt-3 [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-text-secondary [&_li]:text-sm [&_li]:text-text-secondary">
        <h1 className="font-display text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mt-2 text-xs text-text-secondary">Last updated: {new Date().getFullYear()}</p>

        <p>
          Your privacy matters. This policy explains what we collect, why, and the control you have.
          The short version: <strong className="text-text">we store your chats to give your companion
          memory, we never sell your data, and you can delete everything.</strong>
        </p>

        <h2>What we collect</h2>
        <ul className="mt-3 list-disc space-y-1.5 pl-5">
          <li><strong className="text-text">Account:</strong> email, name, hashed password.</li>
          <li><strong className="text-text">Conversations:</strong> your messages, Aria&apos;s replies, voice notes, and photos you send (used for context/vision).</li>
          <li><strong className="text-text">Memory:</strong> durable facts extracted from chats so your companion remembers you.</li>
          <li><strong className="text-text">Usage:</strong> message/API counts for quota enforcement.</li>
          <li><strong className="text-text">Payments:</strong> handled by our processors (Razorpay / Stripe); we store only the transaction reference and plan, never card numbers.</li>
        </ul>

        <h2>How we use it</h2>
        <p>
          To run the Service: generate replies, remember context, enforce plan limits, process
          payments, and prevent abuse. We do not use your conversations to train models sold to third
          parties, and we never sell your personal data or use it for advertising.
        </p>

        <h2>AI processing</h2>
        <p>
          Replies are generated by our own model running on our infrastructure. Photos you send are
          described by a vision model on our servers to give your companion context; the description is
          stored with the conversation.
        </p>

        <h2>Data retention &amp; deletion</h2>
        <p>
          Conversations and memories are kept until you delete them. You can delete any conversation
          from the chat sidebar, remove individual remembered facts from your Account page, or delete
          your entire account (which erases all associated data) by contacting support.
        </p>

        <h2>Security</h2>
        <p>
          Passwords are hashed with bcrypt, API keys are stored only as SHA-256 hashes, and media is
          served through authenticated, per-user access checks.
        </p>

        <h2>Your rights</h2>
        <p>
          Depending on your jurisdiction, you may have rights to access, correct, export, or delete
          your data. Email <a href="mailto:privacy@aria.chat" className="text-accent-strong hover:underline">privacy@aria.chat</a> and we&apos;ll help.
        </p>

        <h2>Children</h2>
        <p>Aria is for adults (18+) only. We do not knowingly collect data from minors.</p>

        <h2>Contact</h2>
        <p>
          Questions about privacy? Email <a href="mailto:privacy@aria.chat" className="text-accent-strong hover:underline">privacy@aria.chat</a>.
        </p>
      </article>
    </div>
  );
}
